config/routes.rb
Rails.application.routes.draw do
  resources :forums
  resources :topics
  resources :posts

  devise_for :users

  root 'welcome#index'

  resources :forums do
    resources :topics do
      resources :posts
    end
  end
end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :topics, :dependent => :delete_all
	has_many :posts, :through => :topics

	validates_presence_of :name
	validates_length_of :name, :maximum => 255 
	validates_length_of :description, :maximum => 1000
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic, :counter_cache => true
	belongs_to :user, :counter_cache => true

	validates_presence_of :body
	validates_length_of :body, :maximum => 10000
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :forum, :counter_cache => true 
	belongs_to :user
	has_many :posts, :dependent => :delete_all

	validates_presence_of :name
	validates_length_of :name, :maximum => 255
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @forums = Forum.all
    respond_with(@forums)
  end

  def show
    redirect_to topics_path(:forum_id => params[:id])
  end

  def new
    @forum = Forum.new
    respond_with(@forum)
  end

  def edit
  end

  def create
    @forum = Forum.new(forum_params)
    respond_to do |format|
      if @forum.save
        format.html { redirect_to forums_path }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @forum.update(forum_params)
    respond_with(@forum)
  end

  def destroy
    @forum.destroy
    respond_with(@forum)
  end

  private
    def set_forum
      @forum = Forum.find(params[:id])
    end

    def forum_params
       params.require(:forum).permit(:name, :description, cat_attributes: [:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @topic = Topic.find(params[:topic_id], :include => forum)
    respond_to do |format|
        format.html # index.rhtml
        format.xml { render :xml => @posts.to_xml }
    end 
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params[:post]
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @forum = Forum.find(params[:forum_id])
    @topics = Topic.all
    @topics_pages = Topic.all
    respond_with(@topics)
  end

  def show
    redirect_to posts_path(:forum_id => params[:forum_id], :topic_id => params[:id])
  end

  def new
    @topic = Topic.new
    @post = Post.new
    respond_with(@topic)
  end

  def edit
  end

  def create
    @topic = Topic.new(:name => params[:topic][:name], :forum_id => params[:forum_id])
    @topic.save!
    @post = Post.new(:body => params[:post][:body], :topic_id => @topic.id)
    @post.save!
    respond_with(@topic)
  end

  def update
    @topic.update(topic_params)
    respond_with(@topic)
  end

  def destroy
    #@topic = Topic.find(params[:id])
    #@topic.posts.each { |post| post.destroy }
    @topic.destroy
    respond_with(@topic)
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name, cat_attributes:[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
<p>Forum Name:<br /><%= f.text_field :name, :size => 40 -%></p>
<p>Description:<br /><%= f.text_area :description, :rows => 4, :cols => 60 -%></p>
<div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<h2>Forums</h2>
  <p><%= link_to 'Create New Forum', new_forum_path -%></p>
  <table > 
    <tr>
      <th >Forum name</th>
      <th >Topics</th> 
    </tr>
    <% @forums.each do |forum| %>
    <tr  >
        <td >
          <div >
            <%= link_to forum.name, topics_path(:forum_id => forum) -%> 
          </div>

          <div > 
            <%= forum.description %>
          </div>

          
          <br />
          <small>
            <%= link_to 'edit', edit_forum_path(forum) %>
            <%= link_to 'delete', forum_path(forum), :method => :delete, :confirm => 'Are you sure? This will delete this entire forum.' %> 
          </small>
   
      </td>
    <td >
      <%= forum.topics_count %>
    </td> 
  </tr>
<% end %> 
</table>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chata2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="nav pull-right">
  <li><%= link_to "Home",       root_path %></li>
  <% if user_signed_in? %>
    <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "Settings", '#' %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        </li>
      </ul>
    </li>
    <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
  <% end %>
</ul>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2><%= @topic.name %></h2>
<h3>
  <%= link_to 'Forum', forums_path %>
</h3>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div >
  <p> Subject:
    <%= f.text_field :name, :size => 40 %> </p>
  <p> First post:
    <%= text_area :post, :body, :rows => 8 ,:cols=> 60 %> </p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h2>Forum: <%= @forum.name %></h2>
<h3> Topics </h3>

<p>
	<%= link_to 'post new topic', new_topic_path(:forum_id => @forum) %>
</p>

<table>
	<tr>
		<th>Topics</th>
		<th>Posts</th>
		<th>Author</th>
	</tr>
	<% @topics.each do |topic| -%>
		<tr > 
			<td >
				<%= link_to topic.name, posts_path(:forum_id => @forum, 
													:topic_id => topic) -%>
				<br />
				<small>
					<%= link_to 'delete', topic_path(:forum_id => @forum, :id => topic),
										  :method => :delete,
										  :confirm => 'Are u sure?' %>
					<%= link_to 'edit', edit_topic_path(:forum_id => @forum, :id => topic) %>
				</small>
			</td>
			<td><%= topic.posts_count %></td>
		</tr>
	<% end %>
	
</table>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>